mode: balanced
idle_fan_speed: 1
temperature:
  - start_temperature: 36
    fan_speed: 10
  - start_temperature: 40
    fan_speed: 20
  - start_temperature: 45
    fan_speed: 25
  - start_temperature: 50
    fan_speed: 40
  - start_temperature: 55
    fan_speed: 50
  - start_temperature: 60
    fan_speed: 75
  - start_temperature: 65
    fan_speed: 100
  
# mode: quiet
# idle_fan_speed: 10
# idle_temperature_limit: 35
# temperature:
#  - start_temperature: 40
#    fan_speed: 20
#  - start_temperature: 50
#    fan_speed: 30

# mode: performance