mode: balanced
idle_fan_speed: 10
temperature:
  - start_temperature: 40
    fan_speed: 20
  - start_temperature: 50
    fan_speed: 30
  
# mode: quiet
# idle_fan_speed: 10
# idle_temperature_limit: 35
# temperature:
#  - start_temperature: 40
#    fan_speed: 20
#  - start_temperature: 50
#    fan_speed: 30
